# Generated by Django 4.2.6 on 2024-03-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_savesearches_current_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savesearches',
            name='current_url',
        ),
    ]
