# Generated by Django 4.2.6 on 2024-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_savesearches_current_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesearches',
            name='current_url',
            field=models.CharField(default=None, max_length=1000000),
        ),
    ]
